---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/img
  label: Img
  create: documents
  match: "**/*"
- type: directory
  path: src/prestations
  label: Prestations
  create: documents
  match: "**/*"
  exclude: prestations.json
  templates:
  - new-prestation
upload_dir: img
public_path: "/src/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
